name       : pycrypto
version    : 2.6.1
release    : 4
source     :
    - https://pypi.python.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz : f2ce1e989b272cfcb677616763e0a2e7ec659effa67a88aa92b3a65528f60a3c
license    : Public-Domain
component  : programming.python
summary    : Cryptographic modules for Python
description: |
    Cryptographic modules for Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2013-7459.patch
    %patch -p1 < $pkgfiles/security/cve-2018-6594.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
